# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cm7FvFRzW-ZwAmI0RQdpKo_5ZPcsbO99
"""

#pyramid
def full_pyramid(n):
    for i in range(1, n + 1):
        for j in range(n - i):
            print(" ", end="")
        for k in range(1, 2 * i):
            print("*", end="")
        print()

full_pyramid(5)

#Fibonacci sequence
nterms = int(input("How many terms? "))

n1, n2 = 0, 1
count = 0

if nterms <= 0:
    print("Please enter a positive integer")
elif nterms == 1:
    print("Fibonacci sequence up to", nterms, ":")
    print(n1)
else:
    print("Fibonacci sequence:")
    while count < nterms:
        print(n1)
        nth = n1 + n2
        n1 = n2
        n2 = nth
        count += 1

#palindrome
s = input("Enter a Name: ")
i, j = 0, len(s) - 1
is_palindrome = True

while i < j:
    if s[i] != s[j]:
        is_palindrome = False
        break
    i += 1
    j -= 1

if is_palindrome:
    print("Yes")
else:
    print("No")

#Basic codes
a = input("Enter Your Name :")
b=("Hello",a+"!")
print(b)

def basic_io():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    print("Hello", name + "!")
    print("You are", age, "years old.")

basic_io()